name: Deploy to Hosting ðŸš€

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: ðŸš€ Deploy to Shared Hosting
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: ðŸŸ¢ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Sesuaikan dengan versi PHP hosting Anda

      - name: ðŸ“¦ Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: ðŸ“‚ Sync files (FTP)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Upload ke folder mana di hosting? (misal: /public_html atau /resto-app)
          server-dir: /resto-app/ 
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            .env
            /storage/*.key
